# Generated by Django 4.2.4 on 2023-09-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.TextField()),
                ('image', models.ImageField(upload_to='assets/user_images/')),
            ],
        ),
    ]
