# Generated by Django 4.2.4 on 2023-08-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0002_rename_posts_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="post_image",
            field=models.ImageField(upload_to="post_images/"),
        ),
    ]
