# Generated by Django 4.2.4 on 2023-08-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0003_alter_post_post_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="post_designation",
            field=models.CharField(default="CEO", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="post",
            name="post_image",
            field=models.ImageField(upload_to="assets/post_images/"),
        ),
    ]
